version: 0.2
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      - echo "SONAR_PROJECT_KEY: $SONAR_PROJECT_KEY"
      - echo "SONAR_TOKEN length: ${#SONAR_TOKEN}"
      - mvn verify sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_PROJECT_KEY -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN 
